export const BODY_IT: Record<string, string> = {
  chest: "Petto",
  back: "Schiena",
  shoulders: "Spalle",
  "upper arms": "Braccia",
  "lower arms": "Avambracci",
  waist: "Core",
  "upper legs": "Gambe",
  "lower legs": "Polpacci",
  cardio: "Cardio",
  neck: "Collo",
};

export const EQUIP_IT: Record<string, string> = {
  "body weight": "Corpo libero",
  barbell: "Bilanciere",
  dumbbell: "Manubri",
  cable: "Cavi",
  "leverage machine": "Macchina",
  "smith machine": "Smith machine",
  kettlebell: "Kettlebell",
  band: "Elastico",
  "resistance band": "Elastico",
  "ez barbell": "Bilanciere EZ",
  "olympic barbell": "Bilanciere olimpico",
  "trap bar": "Trap bar",
  weighted: "Zavorra",
  assisted: "Assistito",
  "medicine ball": "Palla medica",
  "stability ball": "Fitball",
  "bosu ball": "Bosu",
  rope: "Corda",
  roller: "Roller",
  "wheel roller": "Ruota",
  "sled machine": "Sled",
  "skierg machine": "SkiErg",
  "upper body ergometer": "Ergometro",
  "stationary bike": "Cyclette",
  "elliptical machine": "Ellittica",
  "stepmill machine": "Stepmill",
  hammer: "Hammer",
  tire: "Pneumatico",
};

export const TARGET_IT: Record<string, string> = {
  pectorals: "Pettorali",
  lats: "Dorsali",
  "upper back": "Alta schiena",
  traps: "Trapezi",
  delts: "Deltoidi",
  biceps: "Bicipiti",
  triceps: "Tricipiti",
  forearms: "Avambracci",
  abs: "Addominali",
  spine: "Lombari",
  glutes: "Glutei",
  quads: "Quadricipiti",
  hamstrings: "Femorali",
  adductors: "Adduttori",
  abductors: "Abduttori",
  calves: "Polpacci",
  "cardiovascular system": "Cardio",
  "serratus anterior": "Serrato",
  "levator scapulae": "Elevatore scapole",
  "hip flexors": "Flessori dell'anca",
  obliques: "Obliqui",
  "lower back": "Lombari",
  shoulders: "Spalle",
  hamstring: "Femorali",
  core: "Core",
  chest: "Petto",
  back: "Schiena",
};

export function tBody(k: string): string {
  return BODY_IT[k] ?? k;
}

export function tEquip(k: string): string {
  return EQUIP_IT[k] ?? k;
}

export function tTarget(k: string): string {
  return TARGET_IT[k] ?? k;
}

export const SEARCH_ALIASES: [string, string][] = [
  ["panca piana", "barbell bench press"],
  ["panca inclinata", "incline bench press"],
  ["panca", "bench press"],
  ["stacco rumeno", "romanian deadlift"],
  ["stacco", "deadlift"],
  ["trazioni", "pull-up"],
  ["trazione", "pull-up"],
  ["lat machine", "lat pulldown"],
  ["rematore", "row"],
  ["pulley", "seated cable row"],
  ["croci", "fly"],
  ["alzate laterali", "lateral raise"],
  ["alzate frontali", "front raise"],
  ["lento avanti", "overhead press"],
  ["military press", "military press"],
  ["spinte", "press"],
  ["curl martello", "hammer curl"],
  ["french press", "lying triceps extension"],
  ["pushdown", "pushdown"],
  ["dip", "dip"],
  ["piegamenti", "push-up"],
  ["flessioni", "push-up"],
  ["squat bulgaro", "bulgarian squat"],
  ["affondi", "lunge"],
  ["affondo", "lunge"],
  ["leg press", "leg press"],
  ["leg extension", "leg extension"],
  ["leg curl", "leg curl"],
  ["hip thrust", "hip thrust"],
  ["ponte", "glute bridge"],
  ["polpacci", "calf raise"],
  ["calf", "calf raise"],
  ["plank", "plank"],
  ["crunch", "crunch"],
  ["addominali", "crunch"],
  ["russian twist", "russian twist"],
  ["girata", "clean"],
  ["slancio", "jerk"],
  ["strappo", "snatch"],
  ["scrollate", "shrug"],
  ["tirate al mento", "upright row"],
  ["corsa", "run"],
  ["cyclette", "stationary bike"],
  ["vogatore", "rowing"],
];
